apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:jVFjd0DltPQ=,iv:JDXF065Hev3posAFF4/TtZ//uZHYC7TLiPzLZykZUAM=,tag:7DncQKNbWuOtFBTz1fAfMQ==,type:str]
    http-password: ENC[AES256_GCM,data:JUBSKn0VLOPnRQVCj+Kp1KHd5Vo=,iv:GTbV2KunIb5u+WYABvxCQlOqRo0O3mSmJXi7GwAu3XM=,tag:+a4OtwIGsFJ4DU6SPXoU8w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:13Z"
          enc: CiQAQ7huFp5ZuMtSDkTdGzluimvVk9nurLuY7LhJ+v35klbcnCcSSQC//AyihuCfms0HsFt9vJWXPXguJ/w5kPU5LOO2xGLql5vRnJ7DvmqscrMPzyL/NJlaZ+FsKNKP9/tghQ5cmWGAk5bt7BKGQ84=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:13Z"
    mac: ENC[AES256_GCM,data:YKkg/UVl+A1dXeT90yaozSr/PYgZb5+dyFRR9TBKzYxZtze5OtGu3OC5j+3DLHIVaoEYYs0Ac3fl9ohlS7x7LkKAYPPAwD6mUhVzPZk0BgsMhyqdo+hEU3iaSD0T+iaFbBGd5jw/if5f3iid33bmnQQQxOLuNhcBSlgJXd8dw+A=,iv:98B08fof/QzLOc8w5HGt4Xq78PeWMCF7BBtrS/DOv6M=,tag:1uUPNqP2uL0Os3KYGclxrg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
