apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:Rnwg1mNaWkM=,iv:658WgZS5kkOD7GUhqKZSYebTJ5guJMYleuomuJkD0wg=,tag:1tQn60bv2LJhCCVboJPTLw==,type:str]
    http-password: ENC[AES256_GCM,data:dAEbOX2KeUFoBjjs3y7nGK1NkuQ=,iv:rByvV8w/QfVNxpAYRpWclNW0dMOXKjX1ZcYHM89smNU=,tag:uQRu8g7uV6F8QX3E4kvobA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:41Z"
          enc: CiQAUhREBx0k+Ph08lSdtztQd5LQWJpyxuFTU9FBZ/hs3zar1Q8SSQD4ANZe3mRAehlNq401cZDo/MXSFMs9vg3CKvccL6cjMDIPUsUZdBVbLpVAqPQSjVicdx+e09PKqdcZyzFKK+nw7SBSZh6yiH4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:41Z"
    mac: ENC[AES256_GCM,data:kthRNgzXSkNXVsyQSj+H0G7Gj9a7PmchBamlSyRwEwzo2EmKKQga7Gp63Q4Ez5Py6c2vIudbhPejtTYo5fZfFpv/qyB9E2PL6LqOQ829dngxXcZuhRGH7fIVOIZdFuBt8OimoINjdX/ZVYpQF8qke4+4CjLcgeG7TXWEZqgoX6M=,iv:I/BX1f+IAMXOI7+/tsIz/i24WziG72iRsPM88gNg2bA=,tag:ykl/B4YV3V6j6EeQBbGc3w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
