apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:oGy2frSWmcE=,iv:4nPpDGrV9qcUTjXhuCHl3Aj+LizcztuDISVbOwIiK+c=,tag:9SEJmP0+RSjB/zF8aS+0sw==,type:str]
    http-password: ENC[AES256_GCM,data:DxCBkRMe0g25ptfLAkh3NQ==,iv:ANiXP1Ab+e207erFmr9clMdELIDTlsA4L5t+Azcd+Qc=,tag:ChECGc1jQXSsU8yToxtL7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-13T13:04:03Z"
          enc: CiQAUhREBx08bhpT/iy+rrhuE8xL/P6fKI4KGRaWa6iOEuZP0mASSQD4ANZeAL3nXDn/DPOUKytAaFjQ/MCDL50HmiLCrlM+ys2Djlz/JXJAVCDuKa4taIOqVmlEkbjxJg5XlxSuSyV6f7EHxu4uPSY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-13T13:04:03Z"
    mac: ENC[AES256_GCM,data:emET06M+0uMJzEgZJSdP6WCYclLuOG70UcQbiIoLcnYH/SNRk96l0eqDeW6o9+G2vB4QjOB8aaCzBnyZ863cqV7YE5CbdoP4cUIyAHDrX/JiUJgsigE2s7dI7blggINy4GwJd2aUlkgqR9ny+3oO6BlCUwHdmPfEBJ6slWdNkDI=,iv:344bWH2qOSqHMQdfFZ9Cp3c+yaAsRwQlXLn+I5Sy+28=,tag:/JwCWh+CLbuLsTFPVrXzJg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
