# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:CCQt3wjUhzY5ZxfDKkoEwqzffNNZlIfq,iv:7WI+R+T7IP6dlGF1kR/cU72djnyehKGH0LawElu3XFk=,tag:I/7wxTcDZNT+G4+CazXwgA==,type:str]
    http-password: ENC[AES256_GCM,data:gSMFF4G4bA10sm9pGePPhzY6Rs+XmQvgI5P210lU2Bge3WDkvIthE5ksq64=,iv:HlnxcZRmadm0GH/fW6VyxsUTxCR2QHwoxd4F+lchS/o=,tag:4fy62nrLCnK0BH4KTTLkng==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T12:00:48Z"
          enc: CiQAhLiU4XwIq2YkLZCrobU/aysqivRGUTju5WlsMhhQTR1/ZMsSSQDOezfyV/3y3snsYyi9YKwfNmLOy6/CbqepUhvUspFI0Bf8744XED8+QReIVOJi4Zir/s/cWx7S3u7bxVh/su82dzo5YFUxAP8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T12:00:49Z"
    mac: ENC[AES256_GCM,data:xK8TRvEQ8/bgUpC20IWF0dmSRjAIyW89rdgpVks+4NygY7llr5Ps/zIEepQmRUgL1xrY5Y7qcJh7Z6XRdrpD7uNiUM2KvPll40SnsPAS1LqgzafbWu5X1/RhGfriQkKbhwc19CR3CCxBTzAxWexcWveHyrlH/1b8BcKK7i2VQTY=,iv:jH84OkXAU5IKK0lAdKdzYYO+PPWcSgqWpknsOKrj1+8=,tag:iqnSTuSaLY86zVK+X0bifg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
