apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:hlWjRgHXOO+q+f3n1+zlXQ==,iv:gLU5vXRz1jEy7hvMYYyl4WZw41+zrbsC6BedBUJnd+8=,tag:+2XmCEjf/RK0iXNEod3FSg==,type:str]
    http-password: ENC[AES256_GCM,data:icUn4sySlF0spfInJBLk1A==,iv:FLWKeunHMwMm6JAAFMW9JaqjItCJs/QH7AJkpW6/APs=,tag:tBLjPdW3OK+n96MYMRYWMA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:41Z"
          enc: CiQAUhREB0aYVP+eThd4Z0or7KmFvm9V711moyGGxlLXEI7+GhcSSQD4ANZeVlkoTENqqXNDxPNI9R3o4RZe5YyyDdzVxGE/Rg6Q7a3PvZl4UKkIBZH36o3iL6GXY2puzjPxsma621Ud692aPPJoJp0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:41Z"
    mac: ENC[AES256_GCM,data:VW2lH6i4/v8wVGelP583QFRbkYFxDLxmXCTPgZDAw/Be01Ckdg0JwqNK1lTVpTtsW01z8xPN7elCtQZRtmiQxK0Uk56NIN1DWRDcGzi/77jdg2mgXTp7Gc3DI5Y84lohE1VqCmfaHmYGg+MR4vK4bt3tHAePbz6zyjlMaGCYH6w=,iv:WtlWHYwfdHyHCOBL2ivS9vB+msW8k9/LX3tt/cleImI=,tag:OUBqIhbKYGkEaq2BJuycTw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
