apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-rtpi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-rtpi
data:
    mqtt-username: ENC[AES256_GCM,data:JFZy7IpbFh0H6+KPMmdLYFndzCpePPWqg/xuZ3AF7mPKmsGBoXEI02BDNTo=,iv:WW4dw6FEoEu7SNwOAF3c2EUe3bxLZpUcYSMCU/4Q4fQ=,tag:RYK9dqdMd/VeNsY07IbZTw==,type:str]
    mqtt-password: ENC[AES256_GCM,data:/p7i1s4PXueZ+sO3fovshQ==,iv:PpNQvQN8vhrVdYg5qV6+7UVh8Pm2HLb3kMscaxnRa20=,tag:K9qDrAj9UMy3Bhs0u4RciQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:39Z"
          enc: CiQAUhREB2nXns/Uaxis8IZSaVLVB37fRrGMSfq+c9OutO8VRlsSSQD4ANZefANS65fEOxvItLPsGJoclCNfTGay759LrwXehx3bQED+MpIsQ0w09TFcxzKemgzg3QyzR1XrsZReHYwOIsEGrXOzmfc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:40Z"
    mac: ENC[AES256_GCM,data:OWYEICd7FFhmLAtv++LI95k196VP235aymrRgcZuDZ9QWt8hU3IdRnuglg31o/f0vuAFho/WF6Y9KC6JTxao/IV5ZZ5ZuwBxRXCYn9AVk1cVOTdrNfwGYgXXPA5k7c5w1EmvdD0gesWtpjM1rcUVS0r7c6yn7uHYOAtM6pnuMj8=,iv:nOboxoYan6ZkrIHNPArCHFqnKzYdZJ1vN4+00IeXdrI=,tag:d98jI8OexkHgeY8Am8oGBg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
