apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-rtpi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-rtpi
data:
    mqtt-username: ENC[AES256_GCM,data:PwPGze/nM4NS8+O02exSoXuPc54RlUdWOJJUN5zUBMg+5z6M,iv:6BeelxsdIaXfylVZXBUHlPWUpa8EJffTJJMa7u/wbV4=,tag:xLOAxcufP0IGARNO4dKK8g==,type:str]
    mqtt-password: ENC[AES256_GCM,data:eLpdxGOt5HE1S+z8BC2eO8c4cgnWT3p0yhoyzg==,iv:C27rYEtZB/eEhDttrjbxDzY3uJCiiKFSirI5XM5FIGc=,tag:vTsZegsknwsm2Fd0c4PlOQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:12Z"
          enc: CiQAQ7huFkSOyxmwoSQ4iuylzZW4DYzOdDMFzRUPudcrsMUm+zQSSQC//AyiiusfzMqAJ/VN9ooX/Ai+imluKaECISZs8r4QI5QksZHg06oteTzFqaWtcczlB+WGaYHB8rbJnWQwDLUjX/SBvmVZnd0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:12Z"
    mac: ENC[AES256_GCM,data:LhhS/4FvEfFHyQZFXrkR708LBZvjdVGtYBB9o7kz8ybneh09sGlWuKmqNOsQM5Km5zrm5ciHnHpi1MkvZvOzDyzP/vYtvwn/hXtjDVbVt0V5YxHbt7IOZg+96jixnSrqBMUFNyUksisy90JKE1MTjrWkNEJOhNIN9rfi1CY2JhQ=,iv:3iBHzpm9vjk7xUEN2zQkDfBxFWH7C7XmIlX7NG3LDwg=,tag:reYcV5D+yV2oop+Sl3AqtA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
