namespace: prod
resources:
  - ../../base

configMapGenerator:
  - name: vehicle-registry-poller-fi-kuopio
    behavior: merge
    literals:
      - "HTTP_PASSWORD_PATH=/secrets/http-password"
      - "HTTP_URL=https://vilkkutestadmin.mattersoft.fi/externalapi/assets/allvehicles"
      - "HTTP_USERNAME_PATH=/secrets/http-username"
      - "PINO_LOG_LEVEL=info"
      - "PULSAR_TOPIC=persistent://apc-prod/source/vehicle-catalogue-fi-kuopio"
      # - "PULSAR_OAUTH2_AUDIENCE=urn:sn:pulsar:waltti:prod"
      - "PULSAR_SERVICE_URL=pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml

