# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:BTMKNq2Swqg=,iv:Ckt01RVqIHcnqi/ekVFv6x0BCFqT7Axtgepxm1gaziY=,tag:En4windHPnf8nOA3yAZ1KA==,type:str]
    http-password: ENC[AES256_GCM,data:Qb3aAb05f7rI2dnbclnw8lj8k4M=,iv:r92LvLdC2lqiHskE7nw2HkChvE3VGLADF2FqiyRMwBk=,tag:3Ch5QsZ/4lw8ufibHQtSQA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T12:55:49Z"
          enc: CiQAhLiU4fWgE6MF0RaWr6hVvj0zJHc3mkr/8BewsyM4LrOSt60SSQDOezfybutW4iLcC1My/AZBdWBInr+mPIwNTc9fEXfmSYbDzbb2p1IknmigLvq0e6BYZd22lQV22lCW1WBmOfLrSMEsxE9vnRE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T12:55:49Z"
    mac: ENC[AES256_GCM,data:LCsZsgXPCNofWR6/fRFiQj3GSIurlZHKIAES2zoRrymOqHmNrxchTsf+rfnH07UIIcSGN3xVTF/Z7UWYhGA717iv7ghqts0VkgVMgeeYvPLZOEMqscYV8kpJitCFa+AVw7aYovgdfK/y9Q54e8qGtSP1jIUgvoLApdDY8Z3ADCU=,iv:RCzExCrhqFJIXzCoWQh/0JOaFNNYkA5J1n1hPOslbkA=,tag:RcpNUqM2AJjCGca4vHttEw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
