namespace: staging
namePrefix: mqtt-mqtt-duplicator-staging-to-dev-
resources:
  - ../../base

configMapGenerator:
  - name: mqtt-mqtt-duplicator
    behavior: merge
    literals:
      - PINO_LOG_LEVEL=debug
      - SOURCE_MQTT_URL=mqtts://mqtts-staging.apc.waltti.fi
      - DEST_MQTT_URL=mqtts://mqtts-dev.apc.waltti.fi
      - HEALTH_CHECK_PORT=8080
      - SOURCE_MQTT_CLIENT_ID_PREFIX=waltti-duplicator-src-staging-to-dev-
      - DEST_MQTT_CLIENT_ID_PREFIX=waltti-duplicator-dst-staging-to-dev-
      - DUPLICATOR_ID=staging-to-dev

generators:
  - ./ksops-secret-generator.yaml
