apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:EGs44VxHLcUjgJodQ6xxqg==,iv:ji/SguNIeXTQem2T3gm1BA0MjqhQw8oBLEekYbTdgvU=,tag:Tmdb2QPD4+ihcfaysjdGaw==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:T1hPnPk5uy6sSJdR5SKe1NSbDLz6DiKFghJfFuGPRhBp77d8uWB4sznCqpceXHxkcS8bBSowdw+HSs1BdWOmdehBwllby0+xAZEhCquy4i+XpPXzJ7TAOg==,iv:Y1Cfi46hvFbe14mx9v1ra7G2TcFyfxYJKbXr6iZ56hc=,tag:C6XCC5qxxH8ocij/IBUrUg==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:430nAia+z0UktM/jAYGbOw==,iv:PaFHc24lv35MSuiE/mQHaKsdexqKdVGwaojRBh955NM=,tag:lLy9QYim/zNl6CjwPDxIlA==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:ZO2vfLYLd1pPxN/GmDDuTtrCLK3aDXQz70Hxkr2xOvWUX/HuynCEReDMDBM/LZZDAaKA9ZSXSxueR4hRDBUhdq8INQ5+nkvlnkDYBW+9Jc6u7LOsPLjx/Q==,iv:FAKTha99U/BjfS1SMW2fop7qR5ZyLLKj+v5aKRbeVGQ=,tag:OAvNYxOPZVNN4sQQFrp6HA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-12T16:34:57Z"
          enc: CiQAQ7huFgjKR1kCd/CCNyxDG/qU9C5nh9BcDKRx4iVCRYG0Yz0SSQC//AyiameQMLu5TIQN1sp29c3gkQJhJLLs6h369ddq52yt54xqYxad5L657f9i39ZXimcIEFDQjwPxstpWQq2ibOpW2N8t0zw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-12T16:34:58Z"
    mac: ENC[AES256_GCM,data:qZmMM0dBzM2Cdc8H2PusNCyQG2qBdtGYJ9O6m3vAXU55B1aOxE10zZo2EWwEDGN1ZXkSI//N+NtFBVl8laBcgwCE4WTTMbUGDC5SzbwKTKQqBExtEyJCjdZYMmypECqWzJeFdMOXBLhjW4h4RrEHY8gLgawZJNhY9H1edUpkJ2g=,iv:zVfwdWdyi0UEpTJ59QM8nmFol3/2uqR3ucZJ4zUkz0s=,tag:6YPQsVN557SBt6PyBAeejg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
