# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:qOsN5muSolDKUuSVnVPMiw==,iv:bRBkul9LQwymJqrF+X+jJ4jG48+HO1RejeLiOBvXPN4=,tag:X6rkL0dzgGQEsXOpkS1IfQ==,type:str]
    http-password: ENC[AES256_GCM,data:MhpWYWwmGoOjdZCYwreN+A==,iv:uxea77vdQKy+sLTa2QQ7zFcYnVQOyqwZgEmmT1NDjug=,tag:SY3St1Nne60+SeKHnDJSNw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T11:58:55Z"
          enc: CiQAhLiU4YAtxYMNLRPGuw37fR0m6JAhpdIwSvosjf1l605JuGASSQDOezfyaC3p706J2ZfjmTYz62wz4X1SIh4uF0o7SfNbcH62zTKHz3NAG38F3kqcRGIOd69L8XyWy72+LDcSfDIXrR2Y0SQZkOA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T11:58:55Z"
    mac: ENC[AES256_GCM,data:mW6yTX+ZH/xhBtx7G4UwlXgTEFBVt1pHLd8+itSWOzfwpDGBW30056re5Rf2wfIkFgbbEAAYdxepslqAUrMDUASEIzDWDCtbUgDcayTa/bRl4vl52gmUcOlpSPlf1GkPfpfYMQfwlaZm1uX9+zb2UJOgWq63WZNlUVrgx78JfUo=,iv:WMnlnUazCduj1DtkjR/7g6jDpmkFJWlDni5Kqv8/3Ag=,tag:kAcvAO7T66WyD0+QdRdmcw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
