# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: mqtt-pulsar-forwarder
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-pulsar-forwarder
data:
    mqtt-username: ENC[AES256_GCM,data:dnpAe9qATpbE2rJI3e3xsbm3Oe0xVeKiULr/3hS/x7grFuUy6V2H5g==,iv:KMRe9OC8olFUldZJfME2H2WkeZDiex/gOihhXNrpxjo=,tag:Kki05hleiMxN+7FnHisjqA==,type:str]
    mqtt-password: ENC[AES256_GCM,data:ufKxFJhW5um4uBbuFxQZXFti4Eestb5P,iv:G3DTDkjBybfPHTTuar+9dt0/4ylsZzS7ROVx4OAfAr8=,tag:8wP88V2xl2/ibNEwWUdI9A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-09T13:56:27Z"
          enc: CiQAhLiU4ddzNEIDQL1P6Y3uNnRbYuUP6Cv65xXI8tWe5K/ZG/gSSQDOezfydC602hJFUsR7WCmlXtPLXPn18ilCThikmQF/ZPeYhr/UF65DlimLDwfA7aNXbjumOJ6hKmtDsXDLqiElhBPaFTZpga4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-09T13:56:28Z"
    mac: ENC[AES256_GCM,data:MDf6bt3+p0gokTEOQTRVOsFfPP7RPNaKQE5wA3/HiPW4F1JS7Ppb2IYAzorVm2HAhS5TDCzEWU6wO0LBdU+tXGwEdR4QnWf/vuMC4bnUUWSqAhSACf9x5qDGxk2Krjw9YxNchjZCt5AXvsf4K2Ja9A76qaSUSS8ilDjhaYRK98Q=,iv:jdHUiUOfcPCyd//jPMRg2+KAjJKr4j2Y21PrhxIBIHQ=,tag:5tHZKXx4hE1UzJxSbhxWpw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
