apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:j6BXWhqZ0qr8LgKou7c24g==,iv:+JYvtkzAE10TPKebd8WB+qPgE3ueBx0C8xCMFv6Pfug=,tag:GY7ujrzUJ+sqrHTkjqeVOQ==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:d/4UkOAJFSLXpGvC9GttQV0aomIGxZLg/YCrnyOMw6bQ5eyXUQwQ8WU0gsp41r/JOEzvC03qHqvBGF0ADGZza9U56S1W4HkgfgeviTq4gpoCmWogkNtKrA==,iv:qZaP4If2xLwL1bsjKu2LXieJxgXQitKvRDzibDRgjSo=,tag:NykwbBuoJq3NdHKdUWKRWA==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:LFgFZ8tOmLWPVYy7bb38ng==,iv:/QBUlARoroTs6THJ9CHBqChhQL/YUrQmzXLrWXTUrnA=,tag:TlEMzxRW0jUCOXvhqzOrTg==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:qtD4vAdFLuHVdsZvVzoLdnmKRpC1ygLkppwqKH2aBeEQYScH88lJT4CvnOappzYc2V7w9jGinfiL3luY,iv:dIhgqVgGOiqsHjlrHG428fb/gv9Pr80twTk2gGbzCGU=,tag:noION+6OvywmOUDIAbxPBQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-12T16:39:08Z"
          enc: CiQAQ7huFnyJyv78Yxr0xRexsTgw7k0Es8vqGdwJoIk9eIwwayQSSQC//AyifpqdXUL8/MvEarlIo5S5nHPB2WUewft4p8chFXgo93Is6ES6SP51m9aD5TczG1+2YVMdNZNlZNTIsPmqa8iYU7pwk24=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-12T16:39:09Z"
    mac: ENC[AES256_GCM,data:NcNuLhZtM9diSusXkOTIe25t1pZYWV+sL/KxIvNA8grnjiS3WnmsD24l/RCczbzzcRg9Y+T47yiGel0Ahn/C+A5k8EoqJ4+PVxKW8Kg8kx2K26DTilx/xdY90ee3lVvdJOYQVydZYelBJPpmRv1pHnWNUqonzjeH2k+7L1pDu3M=,iv:sts2Z7JW5/UTYKbXgIKTpMjKLZmdYgksLQRbvA+Qi+I=,tag:Z21o09gVhub9nu1do41RBg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
