apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-jyvaskyla
data:
    http-password: ENC[AES256_GCM,data:MKYfUi4uhVSiyKhxyS3lo7g3rsqX7kG/e+FGdZMhbIDs+49hvdYt5+uLE/Q=,iv:92xtGbC6/S2VBDqkxkmtZGRDFAvIVFuE9n+h0wabE78=,tag:aWORdhwpaPlFo69hX5/j0A==,type:str]
    http-username: ENC[AES256_GCM,data:ka5NsJOZeVtIQZDK8PtmLjGQxQndyEsi,iv:D7n2FLD9XyKgqvMOHDpi+dRVEWaBi7JYlY3eClOEOzw=,tag:b8MdltJJFeILHYpVKFT9Hw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:14Z"
          enc: CiQAQ7huFpNC/y8g9nx9iHPLRRfRahVgnnGJem7Bg25SHDl4USQSSQC//Ayilip2jOB9vdgbOMGEmDMOStVXYMejLpfYeAVR4SevG26Vd04nVs6r+hUdYCuNXDgcLVZ2fRbq8tMi1/7L2KQz9hde9AU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:15Z"
    mac: ENC[AES256_GCM,data:CbFW26kzoDiBQbnFz9zu4chYQZkShYBLIcea9Ei5KQPNXH7Wl0vAPhk7LdOYrCBaTVCwIPAoaCn+l6dj4BdUeuxcKs8cQReHzNNU6x0UvNxqWUwEAv0ac86dTKcagJwyRod0KoTcj5Yq156Va5gx66zCpzDU4TpLLyWB4JxuK2M=,iv:obWvMmkysyCwqO5l0jWaI8NEMmU6GN78a/GIEhx6W+8=,tag:cnGECqfNWeSgBxGw01lwEw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
