apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:J6mtJqeZWRHpga24tXUjIA==,iv:+pFyr5x+l0uYSbDU96DWsmWpliX3zF4ibp8AtNZll9c=,tag:LPiQoOG4Xvq55asw75pqeg==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:gJdwgWm+tfi97uY+6O2WMiNjha+h9A56KeFFeCjd8tqgfU+0uDLRX6MqExRd7X0TC/rEAqbAjmHH7rke7NF4bjqFK/DGeKMpQmLzXfkzkyQ2Qm/eu9usJg==,iv:r+2UySJC5uXT7ZxbwSj3witr3fd+slGyheBh++YE5KI=,tag:SfqQfSntWa52m9YwacIYtA==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:YahGMvHdp4HgKbfsVUQLHw==,iv:di9o9v0ImsuehveC1IamhvWUZGqom45XBtcbAXclWW0=,tag:jaiIvs8e3wJqOk3EIlwCJA==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:iztFzEX6oi02mzwfG6Ri8/TS51bxilGXY2nY7qM3WkRS/YsTb8OWrYMC252ddoIV/AB855mPR673LmuBQ5aBAP0PCYxFMW8kJdIt80rCORL6xpBt2uAekw==,iv:KqbpJq1dif376dZHCpDjbuubLq/xLBzHPWNaa7wIThk=,tag:PHW+Dt4f4mDLss+I5+UtnQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-12T13:02:09Z"
          enc: CiQAQ7huFkfiCcZDyCgxRQP751QHJIhvDvmN6bE8l8CHsHVzztgSSQC//AyijDqTLl4QFyd11Ju0kJ6w2KefhiuL/agAmJBTmF1x9FxDw5jVeWYp1WIC+Pr3m2wodB731PXOTRrdX5fbru+b4V4kpik=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-12T13:02:09Z"
    mac: ENC[AES256_GCM,data:S3KvCFG5fvdU5YKOMtb9W/IyVHw3UNBrIEcFhCRg/R2GIiybMW1bVjRPnwAh7Lo/ferzj7Ek0lY2B3WUc/NXUvm4Zb7Of2+Wir0KPuo+mQg2X1JP79G87m8fnIq1nCzPtE483KlrLbj3rQX9Evy7ZvPSOqLjD7UAvXt32Jk+W5I=,iv:HXbLgQ/8niytYyG63SBY6tID8dKQy7ZV6u1OpOi/+K8=,tag:18UZUR06kSgPyb3bPCuI4g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
