# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:Kyy4gtvFqI8=,iv:Ns07+PmoPzur3aXTbCOy5elrl9oOaNaztQ4DB0+/eCY=,tag:59v3NamIjNL9PovaEzKSpg==,type:str]
    http-password: ENC[AES256_GCM,data:StCUPGpVly2goIjT74pzfg==,iv:GFtsGCWCHbDIIEtN7iiXCTJIcmOneKNQNY5pQPGg3WE=,tag:Y1Dfc2Q3r4y6sc3S3r928Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-13T13:01:34Z"
          enc: CiQAhLiU4QTRc3p4BmEws2KyxN1gbBWHLkxblwwGTZocbpkBG40SSQDOezfyBKaGTcE2rRXlVCMeEVJWDI+eIi7neEiCB7O0yRo2A2FEhs6n/p9Pu5SqvL6hnlDPqjRpLWTjrFFW+c8P4ztxHDSCpLI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-13T13:01:35Z"
    mac: ENC[AES256_GCM,data:I+mSltkeXewNwHUEEAIHcVu1PD421wi8U1IL8JdOdIp3fDGgm7DbTZhxP+few8KOj1FojYBFspXDAnFpvXkNe21nomrEbzVWHaG1/87S4UBqkxoI0sRHmF3/oqU6Vi+6kH3ZoKagGlBa9/Pv/oZh83VagDfZbxwcjwRjdW/iCww=,iv:C5J1ioNiMp2BSqFhQl/cGG0p/dbT+ituSnd5U3+A7Bg=,tag:Xm9/7X3vfEkLiDUkkp77oA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
