# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:C+Vd/vbLbEk=,iv:r2v+3ZJEwdFUPmv+X1w7x9Innd2E4qlskJyzimnY710=,tag:syOZ+UEsyskc9EhuCVSulQ==,type:str]
    http-password: ENC[AES256_GCM,data:f6o6XhaS4tVZ4Z+zVm+J3IkfQic=,iv:Ik+yvDzKfvriVvE+z1F2kPehyvb+QDU7Duqjl0t3HNc=,tag:v9052tqmytM0ntr7dMTKMQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T12:55:37Z"
          enc: CiQAhLiU4d7ajVr+aE7BHOuUGYDZZF+Kp5V8ytn0Wq9bvespD6kSSQDOezfysbtHJ/hdD8d5nHuCPbO00CaXn6RzrC7TkEczj6I+QLWFupCwG5heKBHqk1NKjLR8Dc5OjRt/al+Bqf2IkfBu3Y1uciA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T12:55:37Z"
    mac: ENC[AES256_GCM,data:4bL3bLDM8hCWTvnM40UNXkhffyeirQsACkPlvhOrWqiY7ZeNDYEUVHB/fPOKKXxSgBgbcPMAxsUs8hvN04S+CWXmFIm/7ejOqStIc2xuZC3oqSSHHsVwkO/XX0sa70XtIZASMYt13Sb/RzDUKec7th2CFuifpLhWVvQjl9hXkM4=,iv:RhAmFDWD5tMIJGLzAkhMnnqMARgygWSqaEYny5sLygs=,tag:UpjqiEjssyLQ6B4rMXYRVw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
