apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:df9+EnEe3MD57k+VDJ2iXVV9hnJ/hqcw,iv:Zmvb0kHzPb7oV7XO2p6WErGUUA0rYeiB0EoE2vYfKcI=,tag:0lPRufYgQAH9Bq/Rx9yTfQ==,type:str]
    http-password: ENC[AES256_GCM,data:H4//WUQ7yWV0FToXtTfM9yczcfh3t926pERXPPPNLqX7f9P3d5rcSM8B6ic=,iv:bDXF9SvmFXtOK29VTMyNHzoZHIAOtNklpJgOQff3Opg=,tag:uIOGf7MZv2DGcoQRUd60/A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:42Z"
          enc: CiQAUhREBywZ/ojns5C6uWyloiddkfVAXqlQJCFd/YOGX/gVhHMSSQD4ANZe+3Xo8MI0IY+ZlT10zWohLHDTobUGBHJYuIpZzkKkAH2IBu95uF/j2ExIyVNQJ2abB0U/g/Lkimd9S+AY2rl7Yno7VgI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:42Z"
    mac: ENC[AES256_GCM,data:f+xOy85my0/75hmFoy1nmrX0IdAYTH8637SHd3M2mndi8m/1cQcJ23Sq/0Jb6XsNLZXEtr4obnu98toznDZwaiEuM9F6ExzquS3rDUKsPzT88N2ukDqtu2+qOsJgk4VpxO9vyrPNIwChjbuqbsBEecvfVW2slZOrj9ikpCZOfDY=,iv:iYBS5hPcEPX8bz8cVRHx/MEPDLuT+YCBc3Rn9fOwbwg=,tag:QGGsLk9gXSbTkMpOEtF2+g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
