apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-rtpi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-rtpi
data:
    mqtt-username: ENC[AES256_GCM,data:0FMfZ7F1r8zjk0MD6y6H9ou6xbPTaesKiPd3bg7OqV9iy0tG5uDzwQ==,iv:/BPFcb7KnesCwbFVC3DzlrLNDI8bVHYw6SgB2ragF/U=,tag:YvQhzlTWJdHw5ifw8azOhg==,type:str]
    mqtt-password: ENC[AES256_GCM,data:NKAxXPLDRvKFPWsHOBUkMTCYyj9fulK+,iv:VGBWT3e7o3RiqOwIbI5CnchSptHceB0ZzSlTjxDJ0i4=,tag:UhvoKss7cvJV9YW6KhtB3g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-09T13:58:15Z"
          enc: CiQAhLiU4UwsHUMmos2FJ9XDndjGCDCDUUN/eKJue1DN4rmc5WwSSQDOezfyiz5LQM1d5oe0hG5vxHIyvBaQKhPTLvZpjBlo0GMRbC9W4Wz4DRy8DDzYwLqfHtWY78OXf47xbpMaQ1EgQp73j0Gk9Z0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-09T13:58:16Z"
    mac: ENC[AES256_GCM,data:u1WqSu4jyBFj02y6ZwvR1oOMgHaAa4dJ8yIOfvC2SNtCaB7BiP7x3OHYipk7efadPlxy5tG9MEEIo2R/if6XAY2AEZjRbvd5Yve38Y0I6kb2L7k6J9T5etJX7v97wUdAwoPi+5NtJ9lJqholbU6i062IemNurx8r6B/bJ5bnPOQ=,iv:Bbxh9RObVz9xg1RJ7ek08+uedYIgWrgDUO3p9kT7joQ=,tag:hxBGSGnLnqi5/MwDbIInIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
