# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-rtpi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-rtpi
data:
    mqtt-username: ENC[AES256_GCM,data:1g0f4Qr1ssrRK2JW3pzdoQ+2PdRJRwKMpxb6nfLXgqM1z9OA9hjr8TN2/qY=,iv:dZ8ry8vz9akMVYxpTEmfPbY+IXHt1r6zSZ+v13eIKjQ=,tag:gNueyk5YkPiaFkjJyJpN5w==,type:str]
    mqtt-password: ENC[AES256_GCM,data:EiwC3IjxXDOLBSDyDGEcxFlVpukPQNe3,iv:Y4tCK9nziaIEeVfDO55bwg1sEXcF2NMP0lim0bmlp54=,tag:NposPB0s942Us0zPivU0yg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T12:50:15Z"
          enc: CiQAhLiU4Wn0wwhNaKdrHlptu9KNd7WFhVYZBdlH/2rG941a3n0SSQDOezfyR9qPISJ/6Z5NYkcG0Cw0jKIKiFimX+HuUXfzxs2R65h02fT+7X5/i39eeTATr5GEIZZLpvXAkrKXgB4TmfOwcC/1y3o=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T12:50:15Z"
    mac: ENC[AES256_GCM,data:pGHFP3ALPst2uo9/OIuFvcJfq5EjaD3Z/y02iuz3uvj4H57STfqDLCCmUj1d8ybqZW96jutX3874BEdlGsMrWozbBWBnzzyXqFyadkv6Sggjw3qr2p8tBSjxAWm/6ZLQbtmNo0xTrWOf9ZKLiypcmKr96wwJcnbswtAksyYhXWw=,iv:SYe2TFhDQ/3vucLYf4UHawJ1XtF2wTEJyPZzHqgXZaM=,tag:1i6GaZm36awccqJyicniYA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
