apiVersion: v1
kind: Secret
metadata:
    name: mqtt-pulsar-forwarder
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-pulsar-forwarder
data:
    mqtt-username: ENC[AES256_GCM,data:Dt6jKX/aMtjvZzQHyT2YjA3LKP6UBvo1ch01LcXapKOAd6Ff,iv:he9NHne/IjRKjkYS4kGLbwmN0whCnHajmzI/npK132Y=,tag:/lNW2l+a8pinKlCoWX2AVA==,type:str]
    mqtt-password: ENC[AES256_GCM,data:dqv250m7CT3h7mflIt6K4YieZM0=,iv:bQLccE58mdB6WyaNVIjHSq2PyDA5l+bAvRPQNH62CNk=,tag:lum8LIupku4HzLTqXa+VYg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:11Z"
          enc: CiQAQ7huFiIkpIVTWYYLxl/MDYsv1KGXoSTtaOzw9kTM7wOFeYQSSQC//AyiRe+t5gMPLeJSiGUT8PQwj5IZcDRHWfeaqGk/oBXtaewdropOgVvhtFGqIJTLol++sZdJEA63agWUxK4VkMe7ZOikkFw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:12Z"
    mac: ENC[AES256_GCM,data:xAk9aoZOVFSqfJ2oT+SmvwO26xM19MkgnISiCxFkpfskD0OxxE+kN90tdEKIxiT5ShgE5v2E1V7FK8MjqrxRjBX328pfiDbVvF6dh8aHxM69aCOl8mnBPODU9ME1Tyevm9lBRosbYbS92TuBJDEvHMopB0jqWV5zrSmjQt7DsFM=,iv:PcPE1HKUiCZIDpbAWYp3ikjHCB4y/DvzWOCEFxoW5/U=,tag:D96qlPAktZmAHXfu9A2T3g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
