apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-raportointi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-raportointi
data:
    mqtt-username: ENC[AES256_GCM,data:ILD+Q7QaGmFNfHki4adCXgxvcu9cGMSxt2G7qmPBiVmmuxbw,iv:Jn9qNqzLcIjQpYk/GMPrw8Tqeqyz4V5QnSS8e6I4MtY=,tag:Kej61RaH0ZtQC9oUOz0b2A==,type:str]
    mqtt-password: ENC[AES256_GCM,data:f+I6DPGpDxlWVCbqss4e4i5EjrUGJxi5zHvg8g==,iv:qFzQuGqNqGK1A+D/FWFTwbJrJAjikimJqeawnU9q1jw=,tag:Z6EWsCMUaP8OYY3JEMEcIQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:12Z"
          enc: CiQAQ7huFuEvhrKvE13M2RqJYDG3MNjGevPWYBlKMb6zhSwOsiQSSQC//AyiYWaweazZXGQ+cyOYBEBAcaa/8GpPDnNd7FbAbonM7CItDpazQeZkjN6DVmOLH3C9/TkHRxVA/xmHiPWfxtOGbXEEaqo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:13Z"
    mac: ENC[AES256_GCM,data:IV4gsu/SeBWJUZfqnVTr4lV439rbOMiJCjSwpr3z95OdgDXQq9HOXtCpovQ/1yy6JlIQ7tuiwNl7Pru91GmaIA8JLVzaN0YxYkn/+Nnfs3z2LY2CLUCAwT88abdhrbKpWmdSKk6+pbyxZm84eY7InOt+RH7jSdZIElquHheFI9M=,iv:cSavOCjzuK0zQOXTLSwRc+eW+w4UCXrNpjsNpHZLJyU=,tag:qv//YPAmr1/Dv/K3dO8T4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
