namespace: dev
namePrefix: mqtt-mqtt-duplicator-dev-to-prod-
resources:
  - ../../base

configMapGenerator:
  - name: mqtt-mqtt-duplicator
    behavior: merge
    literals:
      - PINO_LOG_LEVEL=debug
      - SOURCE_MQTT_URL=mqtts://mqtts-dev.apc.waltti.fi
      - DEST_MQTT_URL=mqtts://mqtts-prod.apc.waltti.fi
      - HEALTH_CHECK_PORT=8080
      - SOURCE_MQTT_CLIENT_ID_PREFIX=waltti-duplicator-src-dev-to-prod-
      - DEST_MQTT_CLIENT_ID_PREFIX=waltti-duplicator-dst-dev-to-prod-
      - DUPLICATOR_ID=dev-to-prod

generators:
  - ./ksops-secret-generator.yaml
