apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:PLrcnfvWs8eafLmXR6TNgQ==,iv:kYWKTDHX+T+96Wpo24aZ1reF3J6Xu8aAblhfiHEQTzs=,tag:ON6AondBJzGXx/u9742mww==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:4kuMcGzmPV1Gf1C1x4noOAdhwP2A9zS+jK5KDVAzXmR89FDTnJ0x7BpO0mvy8N+ngQ3K87n4Y0dH66A1R9+xXDaHy0ztWTiN5GsPCeMVhOQ30u6fKA3PaQ==,iv:4LiIhLaylwndvm3CIxCuhIpIL+Nfr9YTSj/uhAaySP0=,tag:RPiiixx4Mzmw9TPZBS56Lg==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:ovqM3DDZsRiIOXbVJObw7w==,iv:zp8ddb/JL+4ttmUaRgnZ4VCx7wxLewjdJOo2OHXb2o0=,tag:tFbUVkislYXBxqhFhKhfjA==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:xFazLxVQHEpahdeSF3WzTna6kMGnaTvo11jcSs+I1N2G2UrMmXCa0N99NNptMgnPrwonLxYuTgUGpxLO,iv:1t8UDRzTxwTtFYpHMFhil1+0fDsiA8Mrh3MWMz7VweU=,tag:g57Ky8Pa6IVYyjkBOTyjAA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-12T12:53:39Z"
          enc: CiQAQ7huFkkWbB38ICSBwNWQsj3+0rOJNLmUBRspaguR+a8d5NYSSQC//AyioHMrsapQ2By4P/l9hjyvyDYu5MhgDhsi4+8hUTPaSdya4bb4wxKw3WKHOOADcCzKfnDHDGWW7PDf7SOd3b17cN6vBz0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-12T12:53:39Z"
    mac: ENC[AES256_GCM,data:qhbmAM6EJ3FdTOfLQ6dnwGeyvfGE5q6G/NiNkPz3F7qqarsz0Krc+XPrPw86DXZiXtghWOJbnVWh/4AH457EjSTZsOZ7ozR6zAsDRjsvj/kq7jb6PL1cEZWwSAcf7ejEbBCwslssgzdjkgIDWqpCrg45NjYss3Afn2t56/KHra0=,iv:AS5b1aqvIwLzevI+ReEOZ8LrhJg8gcUoC1CuGIugkbY=,tag:hfyuqmgV4ng9PcSzTH4n2g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
