apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:vQnYLA/TdHs=,iv:gjxBA/b5Ge5CtrvDc9cZwQWdCoD9Xi1ZQrpv//pDD/g=,tag:39F2/NazhKE/Zu8byCue/g==,type:str]
    http-password: ENC[AES256_GCM,data:J4WqKryXmLcU1zNGMNYJQg==,iv:hgSJaydiUPqSvojVAs/0yTLykWcpYixw5Sz257PbKxM=,tag:evcwFh0764y2jb0hvLCxhw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-10T15:28:49Z"
          enc: CiQAhLiU4agEUOFE5vBLd1+76zNRE0PTASCLlmJNphW1VjFW3v8SSQDOezfyze1Ymy7dHi7a0HQXRd3e9aFfU3oJH4hXlHXWRb8oScbvbUppN0NADfjwrUHL4HXTXrkcSTlibC86gBo+FhMz8zwBEL0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-10T15:28:50Z"
    mac: ENC[AES256_GCM,data:0eQXEGa+TJlVV7xzFp6NEBT1ek48Wj/QcafpXC/5TvKbjt52yb34FwXBhunX7f7EPnXun4qwIuobBsMroHcT+v9kLqiyD9jzzRj2BmJhV9t47aTIiBveewvyE3oEvmH0yEbVVRiG+DNfTYqKKuEB545GTxF8eJAPw1pa8KQSvpg=,iv:EU0wV+LD+ZFwzEhXnGsux1gtSldhmqlmUKsd319bVz8=,tag:0BNgxMyoolZM/hslQ9djlA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
