apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:FWSUe3RiPBo=,iv:xJeNssyY1oRYphGRD40TiKWNPj7mO9D2h70b6YJNs5A=,tag:HU7Nkbw3gQxRJ/V3OVAIXg==,type:str]
    http-password: ENC[AES256_GCM,data:iPiW+bgLRZB7fN5oBJAV+SgiGJU=,iv:ayTaihyTj8bbRLjx+QzI8pdQ1z0obKYAR/FAQakwuZ4=,tag:wLGaM4r3tOi991olV9RUNw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-17T12:01:33Z"
          enc: CiQAQ7huFi9ii/mZPhhXdxxVIMjMXKz8mSoqCF3Sul++WwKlNIUSSQC//Ayi/GMETLB6wRfBABpm6YofZ7j/+ulH4F1n67grt4hM/6kruvTQsUrVcSdUBOPiXuD9AQmFEWwUep58gn2EAy1petqJkNw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-17T12:01:34Z"
    mac: ENC[AES256_GCM,data:mKF6Jlu6OELzLqQKtSeB3BPJLNeUD+Dakp7ednODqFVB3CoIj2TcqQ7COrFvhpsgT/xsZ2Ljk3QGQmpzGk3mLrOuYYlWfcxrLXCSzf81TKQbsJSXM5mlfNkitmL0MmVSMdosfI08fqZVoGjaXcuHzFcDQtF9blGTbw1afQhgPvg=,iv:i9uGU3xqEiblF7XBK4XxsHhy+/a5U1p5BJvHrYpg1d0=,tag:KmvHaz3zhyXog8nX9MRB1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
