apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:tZh9rZRC1+g=,iv:00PbeGE6a0ucGl92FU5OD18s/+WE8IoUpgrU4v4Le5M=,tag:OOCnu3w+OIM9LRKBL14XQw==,type:str]
    http-password: ENC[AES256_GCM,data:Z7ziv4+JP7hHtObedlw6KGztEUQ=,iv:jSWjUi09yyYwP2YD2qn0yc1NSiqUiOGb7nvLpyytLmE=,tag:AD/1l+tbeT5PP40g+6xrfQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:13Z"
          enc: CiQAQ7huFifyw4PlgzNAnB81F0WWdEDgALdWqXXrdJBWn01hds8SSQC//AyizJEm2XOOmhEfSqZseSXgoXrAmbZdd/yZEYnYFk6dStCGsYrvztK24SnWVfXKWyTigZD5GyMVUnGBW2UANq9F7JTbrQ8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:14Z"
    mac: ENC[AES256_GCM,data:S44vN+0paK3C8GAP0SK63utkmixJa+EcMOHztnKhus83u2RU6QbZYrR35ljuQNKzRZ/U+a8ZKmPSToytGTdQsOsBDe2gJkRGsB6XPYjpulR3mUBIBaUWY997QrNCIxJ/CpAxF8UYqMLUsAvMPcI0alYhJ/3TEk+uVlfaBtKpS00=,iv:z4VK4ow2L82yacHf9q0jB9QT1DiQhXwu5iiGJWMkLhA=,tag:LYs8glgFUbIpIuzpeNCtcg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
