# NOTE: This file needs to be encrypted with SOPS using prod-specific keys
# Update the GCP KMS resource_id to point to the prod key ring
# Encrypt the actual secret values with SOPS for prod environment
apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-raportointi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-raportointi
data:
    mqtt-username: ENC[AES256_GCM,data:zVIIC9qZODet/wzlPire9bkzy+x3M0aLQaverZiFGilfile1t50XDbNwjoQ=,iv:jWMPBIjZfLk8ShYzwEiJObY3l6C7bw3iSuWFpN2oS14=,tag:hzzfv0M30cV/pHYF/J60Lg==,type:str]
    mqtt-password: ENC[AES256_GCM,data:sT2oa7ThD9iKKVuNOzoMF05X6vdtTC2T,iv:N5auwwUCtiW1Tgo6Jhw6DyXu1t2cu4oopSltIc+Eef8=,tag:+z3KGHdg4Ca/eI6GiKgnvw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-03T12:39:34Z"
          enc: CiQAhLiU4YiJ+T3MDk9MWhDK45f7fRjmHoXjvLTNpEZNmd/YD7ASSQDOezfy47UzF37JP7i2nHGEuPbtR9aCCdcAjoJzApu5eUx4H/cWwIL2BybK2xqod/9R4zguzN7VTs5OltaFCq6QewkACrJjXmQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T12:39:35Z"
    mac: ENC[AES256_GCM,data:Yx8REM3pPRM9xJ854pUBAYQapIDiJGPHlkTGn2+AzWTG0LXb1TCIoSCrNkBxcq7RldpuJFErUYyDLZUSnF2yyAF4ig8hktRezg1DfllyWU7Nc6K4ogB9uRijMUpAoq55TZ/3lGmsJJsRVIKfwj/YB0vbfXdI3Iz6GovdRiQ1DdQ=,iv:bRVk/tkJX+dCZCm9Dw5ho29vsPe042p4DmCWw5AVRdc=,tag:035OzbjVMPXMsKxjQH1gUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
