apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-raportointi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-raportointi
data:
    mqtt-username: ENC[AES256_GCM,data:MY7nb/Ms/Ps3eejwUgVpC9TX9QNwYKLr/R4TMHg5oWlPocNcwRuf+Q==,iv:NsYOWt7BnnPNiXo1nxJQCQyjs8skpzjgmPuUVS5Zp9g=,tag:YJ8Mpi053Jer5t6dIBQd/w==,type:str]
    mqtt-password: ENC[AES256_GCM,data:BIsbltIDdNtUvXMuu5j8U0Nl4ydiELnY,iv:mkhsm9kQkJR74amfPFNMDq3jde+n5aVYNyhZ+rtS898=,tag:hTB3UCJqWvUKRcw9gWO5tw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-09T13:58:15Z"
          enc: CiQAhLiU4XYcrJkPEkVc9JgsIzgg0yYDSdk6PqGNcGVRD9pZjVASSQDOezfyHfq6tfDd9vfVB1BinnnU46CR1jLbPY1WBrI2qy6xsynIE6+UiVDt5qa08Gh2fOfkHjvf+NfR/RqjAxzPI4w1B5pyzLc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-09T13:58:15Z"
    mac: ENC[AES256_GCM,data:u19PMiF8PQc4Cg9cXA/jNFSzg4zXFycFs5UdH9ZWT+NjnNJbpX/9xsMYEcGIEBU2YShBpUHZ4PFPwudC2qIwx4bMsEv8dcAzwIqs3oYg8tNDopLGxP+lyxKbxWOTMzUA7ZEiQ9oZplZKlJHTLjyy/YdmZunrkf9jdh2bhtir6Jk=,iv:Tp+oFIF+Zl4yL/najNGf5WVb7iNHzkHE7WqGeDq4XNA=,tag:YPrjk3aWf9S/asQA3qdruA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
