apiVersion: v1
kind: Secret
metadata:
    name: pulsar-mqtt-forwarder-raportointi
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: pulsar-mqtt-forwarder-raportointi
data:
    mqtt-username: ENC[AES256_GCM,data:nx8JAyzn1wCfohCYL90nrK6eSaCu2TjC+SlEfV5mLA6spjlp8oM5SB4Haqg=,iv:UZf4Gpxa+0XqDTQXT3ZglgUCU9uYlMtvYlRTCDIpaZI=,tag:evRn7GPweESwmxTb8ce23g==,type:str]
    mqtt-password: ENC[AES256_GCM,data:MAcf0zucip7NQAoYQhGxSw==,iv:m6y+QlFhkr9J7CT6AzDNVbwkhwGk8t09u3SlPhFZh+A=,tag:GRRhg6esKzzVqgTDmyfE0g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:40Z"
          enc: CiQAUhREB3R+cn5e7FoloLoa3KBlu8hxqZFF0dNSewi/gTq4BuwSSQD4ANZeVGr66OnjMPsHZiMykaO2cAanXQYKn972a0SoRYcIWV+a8xkIgXuo60KHW6kDxvyR/jf+/RX2Zz/ECiUs0wdrK/tkuqA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:40Z"
    mac: ENC[AES256_GCM,data:RBjRziVKsgDt8O+SuUwPHCEpzjHXPFmlVNkgwl5GjhaNjt/ReaAhOtkqC98RhafvLUgW010u54TOM0bvomxEfnVDJm7s/lMFfme7SP4fyM89lh6+HoFCixmb1p3qreKfrouMwuvhTyltDossdG2nE2q1SB7F8625M+JCyfZwsdI=,iv:/nh4YE5z0XCreKEtaKhMuzBj+hhmBsUcZrb7IiTICVU=,tag:VYlPiLkLu3UGUfX/IEX0vw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
