apiVersion: v1
kind: Secret
metadata:
  name: mqtt-mqtt-duplicator
  annotations:
    kustomize.config.k8s.io/behavior: replace
  labels:
    app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
  SOURCE_MQTT_USERNAME_PATH: PLACEHOLDER
  SOURCE_MQTT_PASSWORD_PATH: PLACEHOLDER
  DEST_MQTT_USERNAME_PATH: PLACEHOLDER
  DEST_MQTT_PASSWORD_PATH: PLACEHOLDER
