apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:fnQxK5AR9uM=,iv:geq3ybRDeZsm8A2LNI3kDdVALbNuDuVpMJUws02bkvk=,tag:6sMm2ylyglz9QeSYUBV9GQ==,type:str]
    http-password: ENC[AES256_GCM,data:QzXc1zagemqUKHTfSnLGvctl+0Y=,iv:AFsmWCEsgLx2u4U9A+KwTUGMpsdYxpRQmToKq1VubwY=,tag:bDPpz/qsA4/N+7Hb0t7L8A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:40Z"
          enc: CiQAUhREBy7w8o90FpjoXfE4LQeskjEyVJVmMGkwTZ4QyaShAB4SSQD4ANZeCk6AAZrffuSj130nwrR98P9sOF9nkpJXhtJkvUfUdIkhSUuwO5IjsCbfNUMhP7SKFy9Ruyap0IiQqYBD/Y7HJxOpYvs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:24:41Z"
    mac: ENC[AES256_GCM,data:eNYcSrziDd1pdZp1Mr+L9ytwlektOQH8naoev59gFNgI5xjUEVpTnqU/7tMECMZsfE6M29Azzy9LzNSbI4Q8fTyu39yx42twyffYo11o8F1H8w5FfyPaOXkrV+4qLqSxnZhtxuRE0aSoOX1je19eI88zjYvJhTSEEw+gZUweoD0=,iv:Bm+d3r6uECe35lQnKwCt5LGvO5EJ0fUGGEIsvqZmkkM=,tag:Jc+ww7esDmuedvwBlbmxzw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
