apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-kuopio
data:
    http-password: ENC[AES256_GCM,data:qf3P3blcIo5pR0Eo4SZaXQ==,iv:Fzv9TfxjwsWmHNXWDhGwPauxL3TJNkfa/arSCue6b/4=,tag:ANpA8/6hXIt4vshGKxvcDQ==,type:str]
    http-username: ENC[AES256_GCM,data:uNm1WSohNEtWsnWjfZ+6Bg==,iv:2vHEwiX4TMrxok1rHrNJwfHWBaNvL9RNaXCf5t4gqPU=,tag:Ann+52takhHFZQzguy6sig==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:14Z"
          enc: CiQAQ7huFgUqHw8zLTozT4agHWfeoNUfevSMvY6wKikGmI3ei2kSSQC//AyiiFeuVj9ObElm6ei2ivd9hnnYmOMU4iHSNR92oN+tpVkfR/2bHv9Dxmsq/kt5Fzfn/8hdbwQaVyivY6nLv8xbVkzh5pM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-27T12:11:14Z"
    mac: ENC[AES256_GCM,data:zNkqhiuJ7rlqBvLDzjIexuLK4jzB4eVT2GxfUVXvKx2aT2G6QxEPYrHKougXtl0j6IjLNZl0FTVI09EY7So0nMLjTVZsvuwKng8i26Q3VQqJYidxdoZ74+KL7t+dbIgL6eeveTBCPefiyY5uxQ88c/RrsMMPEFb5LFoUddP4hqg=,iv:QRcxgc2XKjhEa+KtsUS0PbSSA/srx1VesPPTAyDCOFc=,tag:qbFdYiKal+BoKc97H6VxSg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
